export const TIPOS = {
  FuenteDatos: Symbol.for("FuenteDatos"),
  RepositorioImagen: Symbol.for("RepositorioImagen"),
  RepositorioPreset: Symbol.for("RepositorioPreset"),
  RepositorioEjecucion: Symbol.for("RepositorioEjecucion"),
  RepositorioEntrenamientoYolo: Symbol.for("RepositorioEntrenamientoYolo"),
  RepositorioImagenDataset: Symbol.for("RepositorioImagenDataset"),
  RepositorioTipoEtiqueta: Symbol.for("RepositorioTipoEtiqueta"),
  RepositorioEtiquetaImagen: Symbol.for("RepositorioEtiquetaImagen"),
  RepositorioDeteccionImagen: Symbol.for("RepositorioDeteccionImagen"),

  ClienteCv: Symbol.for("ClienteCv"),

  ServicioCatalogo: Symbol.for("ServicioCatalogo"),
  ServicioImagenes: Symbol.for("ServicioImagenes"),
  ServicioProcesamiento: Symbol.for("ServicioProcesamiento"),
  ServicioOcr: Symbol.for("ServicioOcr"),
  ServicioPresets: Symbol.for("ServicioPresets"),
  ServicioEjecuciones: Symbol.for("ServicioEjecuciones"),
  ServicioCandidatos: Symbol.for("ServicioCandidatos"),
  ServicioEntrenamientos: Symbol.for("ServicioEntrenamientos"),
  ServicioDataset: Symbol.for("ServicioDataset"),
  ServicioProcesamientoDataset: Symbol.for("ServicioProcesamientoDataset"),

  ControladorCatalogo: Symbol.for("ControladorCatalogo"),
  ControladorImagenes: Symbol.for("ControladorImagenes"),
  ControladorProcesamiento: Symbol.for("ControladorProcesamiento"),
  ControladorOcr: Symbol.for("ControladorOcr"),
  ControladorPresets: Symbol.for("ControladorPresets"),
  ControladorEjecuciones: Symbol.for("ControladorEjecuciones"),
  ControladorCandidatos: Symbol.for("ControladorCandidatos"),
  ControladorEntrenamientos: Symbol.for("ControladorEntrenamientos"),
  ControladorDataset: Symbol.for("ControladorDataset"),
} as const;
